INSERT INTO Achievement (id_achievement, name, lore, difficulty) VALUES (1, '1ère année', 'Tous les défis de la première année !', 1);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (2, '1er semestre', 'Tous les défis du premier semestre !', 1, 1);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (3, 'I was here, 1st edition', 'Assister à tous les cours (sans exception) du S1', 3, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (4, 'Distraction', 'Ne pas sortir son téléphone pendant les cours de M. Lucci', 3, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (5, 'What the boats', 'Finir le TP Bateau de M. Lucci', 1, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (6, 'Algortithms master', 'Finir à temps tous les TP d''algorithmique', 3, 5);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (7, 'Financial game', 'Finir votre jeu créé pour le TP d''économie', 1, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (8, 'HTML is easy', 'Obtenir une note inférieure à 10/20 à un TP de HTML (ne le faites pas exprès !)', 3, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (9, 'Power of grids', 'Participer au TP-TD sur Excel avec Mme Mercier', 1, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (10, 'The language of wizards', 'Finir le TP sur le langage LaTeX de Mme Mercier', 4, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (11, 'French master', 'Avoir une note supérieure à 15/20 au DS d''orthographe de M. De Sauza', 3, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (12, 'French god', 'Obtenir la note parfaite de 20/20', 4, 11);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (13, 'Is this programming?', 'Installer un CMS pour le projet', 2, 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (14, 'Definitely not programming', 'Finir entièrement son site vitrine pour le projet', 4, 13);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (15, '2ème semestre', 'Tous les défis du deuxième semestre !', 2, 1);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (16, 'I was here, 2nd edition', 'Assister à tous les cours (sans exception) du S2', 3, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (17, 'Is he useful?', 'Recevoir une aide utile de M. Bettinelli', 1, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (18, 'Switching roles', 'Lui faire découvrir quelque chose', 3, 17);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (19, 'Schemas master', 'Avoir une note supérieure à 15/20 à un DS de COO', 4, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (20, 'Schemas god', 'Avoir 20/20 à un DS de COO', 5, 19);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (21, 'Chess master', 'Finir le TP Cavalier de C dans les temps', 3, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (22, 'Killing network', 'Ressortir vivant des TP de Réseau', 1, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (23, 'Organisation master', 'Faire un bon schéma Gantt Project', 1, 15);
INSERT INTO Achievement (id_achievement, name, lore, difficulty) VALUES (24, '2ème année', 'Tous les défis de la deuxième année !', 2);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (25, '3ème semestre', 'Tous les défis du troisième semestre !', 3, 24);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (26, 'I was here, 3rd edition', 'Assister à tous les cours (sans exception) du S3', 3, 25);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (27, 'You''re now Linked In', 'Créer un compte LinkedIn en cours de PPP', 1, 25);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (28, 'Friendship power!', 'Avoir plus de 100 relations sur le réseau', 2, 27);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (29, 'C master', 'Ne jamais poser une seule question au prof/intervenant en TP', 4, 25);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (30, 'C god', 'Finir à temps un TP de C avancé', 2, 29);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (31, 'Drawer master', 'Avoir une note supérieure à 15/20 à un DS de Gestion des SI', 4, 25);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (32, 'Law has no secrets for me', 'Suivre tous les cours de Droit des TIC', 4, 25);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (33, 'Retranscripting', 'Prendre en note l''intégralité du cours de Droit des TIC', 4, 32);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (34, 'Not very straight of you', 'Obtenir une note supérieure à 8/20 à un DS de Droit des TIC', 2, 32);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (35, 'Wanted: marks', 'Revoir les copies des DS de Droit des TIC', 5, 34);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (36, '4ème semestre', 'Tous les défis du quatrième semestre !', 2, 24);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (37, 'I was here, 4th edition', 'Assister à tous les cours (sans exception) du S4', 3, 36);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (38, 'Android master', 'Faire fonctionner Android Studio du premier coup', 3, 36);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (39, 'Android God', 'Ne jamais rencontrer aucun problème avec Android Studio', 4, 38);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (40, 'Dedicated for the team', 'Être présent tous les jours consacrés au projet', 2, 36);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (41, 'Reaching the end', 'Finir entièrement votre projet', 4, 40);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (42, 'Internship master', 'Trouver un stage avant le Speed Meeting', 4, 36);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (43, 'Any internship?', 'Participer au Speed Meeting', 1, 42);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (44, 'Peaceful place', 'Faire un stage avec des missions qui vous intéressent réellement', 3, 43);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (45, 'The chad writter', 'Faire son rapport de stage en LaTeX', 4, 43);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (46, 'Internship god', 'Obtenir une note de stage générale supérieure à 15/20', 3, 43);
INSERT INTO Achievement (id_achievement, name, lore, difficulty) VALUES (47, 'Achievements globaux', 'Tous les défis impossibles à placer spécifiquement', 3);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (48, 'Weeb year', 'N''avoir aucun Weeb dans la promotion', 5, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (49, 'Give my money back', 'Se faire arnaquer par la machine à café', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (50, 'Look, it''s printing!', 'Imprimer un document à l''IUT', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (51, 'Printer master', 'Vider son compte impression tellement vous avez imprimé', 4, 50);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (52, 'Session hacker', 'Arriver sur un ordinateur avec la session de quelqu''un d''autre d''ouverte ', 2, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (53, 'Discord hacker', 'Arriver sur le compte Discord de quelqu''un d''autre en le lançant à l''IUT', 1, 52);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (54, 'New friend?', 'Recevoir un message privé Discord de la part d''un prof', 2, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (55, 'Databases master', 'Réussir entièrement un TP de Base de données', 3, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (56, 'We are the gamer', 'Participer à une LAN Minecraft à l''IUT', 3, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (57, 'Jokes on you', 'Ne faire aucun meme sur les profs de l''IUT', 5, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (58, 'Dreaming of code', 'Participer à la nuit de l''info depuis l''IUT', 2, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (59, 'Ah, you noob', 'Battre un prof lors d''une compétition de programmation', 4, 58);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (60, 'Look, an error!', 'Obtenir sa première erreur de programmation', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (61, 'Segfault', 'Ne jamais avoir de Segfault en C', 4, 60);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (62, 'Indentation error', 'Ne jamais avoir d''erreur d''indentation en Python', 3, 60);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (63, 'NullPointerException', 'Ne jamais avoir de NullPointerException en Java', 4, 60);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (64, 'You''re the best', 'Majorer la promotion (top 5)', 4, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (65, 'Food break', 'Manger au Crous', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (66, 'Form spam', 'Remplir (sérieusement) un questionnaire de GEA / TC', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (67, 'Attack is the best defence', 'Répondre au mail donnant le formulaire pour faire remarquer toutes les erreurs', 2, 66);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (68, 'It''s your turn now', 'Créer son propre formulaire dans un but de diffusion', 2, 66);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (69, 'Reading master', 'Lire entièrement un des livres demandés pour les cours de Communication', 1, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (70, 'Sweat dreams', 'Ne dormir dans aucun cours', 2, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (71, 'Early Leaving', 'Voir M. Lucci partir de son cours avant la fin de l''heure', 4, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (72, 'The impossible miss', 'Vivre la mythique expérience de M. Lucci absent', 4, 71);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (73, 'Night bird', 'Recevoir un mail de Mme Mercier à/après 23h', 4, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (74, 'Nighter bird', 'Répondre à son mail (de manière utile) tout aussi tard', 2, 73);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (75, 'Dedicated student', 'Être délégué•e au moins une année', 3, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (76, 'Our beloved', 'Être délégué•e toutes les années', 4, 75);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (77, 'Coding life', 'Passer un cours avec M. Genthial sans qu''il ne code ni n''utilise le shell', 5, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (78, 'Confused stonks', 'Avoir un contrôle de M. Genthial noté sur 20 (pas plus, pas moins)', 4, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (79, 'I was here, boss edition', 'Assister à tous les cours (sans exception), tous semestres confondus', 5, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (80, 'The end?', 'Passer tous les semestres sans seuil', 2, 47);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (81, 'The end!', 'Obtenir son DUT<br>Bien joué, vous avez fini !', 1, 80);
INSERT INTO Achievement (id_achievement, name, lore, difficulty) VALUES (82, 'Spéciaux profs', 'Tous les défis liés aux profs directement', 3);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (83, 'M. Objois', 'Tous les défis liés à M. Objois', 3, 82);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (84, 'Network master', 'Avoir une note supérieure à 15/20 lors d''un DS de M. Objois', 3, 83);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (85, 'From Hawaii to UDP', 'Comprendre tout le cours de réseau', 3, 83);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (86, 'Defeat the boss', 'Reprendre M. Objois lorsqu''il fait une erreur', 4, 83);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (87, 'Catch them all, Objois edition', 'Collecter toutes les phrases cultes de M. Objois', 4, 83);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (88, '"On verra ça plus tard"', 'Si celle-ci vous ne l''entendez jamais, inquiétez-vous', 1, 87);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (89, '"Alors, ça ping ?"', 'Clairement, non, ça ne ping pas', 2, 87);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (90, '"J''aime quand vous parlez comme ça"', '( ͡° ͜ʖ ͡°)', 3, 87);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (91, '"C''est facile, vous savez faire"', 'Généralement, non, vous ne savez pas', 3, 87);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (92, '"Personne ne sort avant 1/2 heure"', 'Bloqué•e•s pour un bon moment', 4, 87);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (93, 'Mme Constant', 'Tous les défis liés à Mme Constant', 4, 82);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (94, 'High pitched prank', 'Garder son sérieux en entendant sa voix pour la première fois', 4, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (95, 'Is last minute late?', 'Ne pas faire les TP de comptabilité au dernier moment (1 semaine avant)', 4, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (96, 'You will not survive', 'Lire intégralement un polycopié', 5, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (97, 'Listening master', 'Écouter un cours complet sans distraction', 4, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (98, 'Wait, that''s illegal', 'Appliquer toutes les règles de diaporama de M. De Sauza aux diaporamas de Mme Constant', 4, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (99, 'Catch them all, Blandine edition', 'Collecter toutes les phrases cultes de Mme Constant', 4, 93);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (100, '"Un p''tit appeeeeeeeel"', 'Sans doute la phrase que vous allez le plus entendre de votre vie', 1, 99);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (101, '"Vous sortez vos polycop''"', 'Vos compagnons de route que ne lirez jamais, ne mentez pas', 1, 99);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (102, '"Vous sortez vos PCG"', '"PCG" ou "Plans comptables", les deux fonctionnent', 2, 99);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (103, '"[prénom] ? Iel est pas la [prénom] ?"', '"[prénom]" désigne n''importe qui, "iel" étant la forme neutre de il/elle', 4, 99);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (104, 'Mme. Metge', 'Tous les défis liés à Mme Metge', 3, 82);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (105, 'Balanced diet', 'Recevoir un bonbon de sa part (pour bonne participation)', 2, 104);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (106, 'Free slur', 'Se faire insulter par Mme Metge', 3, 104);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (107, '"I am agree"', 'Lui sortir cette phrase mythique (attention aux conséquences)', 1, 106);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (108, 'Catch them all, Metge edition', 'Collecter tous les TIC cultes de Mme Metge', 4, 104);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (109, '"ui ui"', 'Quand personne ne répond, il faut bien qu''elle réponde à votre place', 1, 108);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (110, '"Yes? Yeeeees"', 'Idem, mais en anglais', 1, 108);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (111, '"Loulou"', 'Se faire appeller "Loulou"', 2, 108);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (112, 'M. Charensol', 'Tous les défis liés à M. Charensol', 2, 82);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (113, 'Sorry I''m late!', 'Passer un de ses cours sans que personne n''arrive en retard', 1, 112);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (114, 'Ha! You noob', 'Avoir moins de 10/20 à un de ses contrôles alors qu''il "a été très gentil"', 2, 112);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (115, 'Forbidden phone', 'Recevoir "Les téléphones portables sont interdits en CM, TD et TP !" de sa part', 2, 112);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (116, 'Stalking', 'Le voir ranger son vélo dans son bureau au moins une fois par jour de la semaine', 4, 112);
INSERT INTO Achievement (id_achievement, name, lore, difficulty) VALUES (117, 'Spéciaux distanciel', 'Tous les défis à effectuer lors des cours à distance', 3);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (118, 'Quizz master', 'Finir premier du classement lors d''un quizz Kahoot', 3, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (119, 'Poll intensify', 'Passer un cours avec M. Charensol durant lequel il ne fait aucun sondage', 4, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (120, 'Hello world', 'Activer sa caméra durant toute la durée d''un cours', 3, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (121, 'Wrong place', 'Se tromper de lien de cours (de manière non intentionnelle)', 2, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (122, 'Quiet place', 'Passer un cours avec Mme Constant sans entendre ses enfants', 4, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (123, 'Ghost roleplaying', 'Ne sécher aucun cours dans lequel le professeur ne fait pas l''appel', 3, 117);
INSERT INTO Achievement (id_achievement, name, lore, difficulty, parent_id) VALUES (124, 'Above us', 'Suivre tous les cours en distanciel sans aucune distraction (jeux, vocaux, messages, internet...)', 5, 117);
